server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: org.ethan.cloud.entries
  mapper-locations: classpath:mybatis/mapper/**/*.xml
spring:
  application:
    name: micro-cloud-dept-8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost/cloud01?characterEncoding=utf8&useSSL=true
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-idle: 5
      max-wait-millis: 200
      test-while-idle: false

